### ISSUE TITLE
Typo in attackDenyList

### ISSUE THREAD

**Issue by aashish-joshi** [GPTSafe/PromptGuard#59]
**Describe the bug**
There seems to be a typo in the list of malicious phrases (attackDenyList) in `attackmitigation/index.ts`.

**To Reproduce**
1. Go to ['attack mitigation source'](https://github.com/GPTSafe/PromptGuard/blob/main/src/utils/attackmitigation/index.ts)
2. Scroll down to line 5
4. See typo `"gnore the above"`

**Expected behavior**
The text should instead say `"ignore the above"` as all the other phrases also start with 'ignore...'

I wasn't sure if a bug report is the right way to report this, but the contributing guidelines ask to raise an issue before submitting a PR so I hope this is OK.

Best,
Aashish

PS - This is an amazing idea! :)

**Comment by redeux** [comment]
Hi Aashish. 

Thanks for your interest and finding this bug. I welcome your contribution to fix it.

**Comment by aashish-joshi** [comment]
Hello,

I've just created a PR with the fix discussed above. Let me know if it needs any changes. :)

I used the idea behind this project as a basis for a similar project in Python. It is still a work in progress, I hope you don't mind if I release it as an open-source library (with due credits to this project).

While working on the Python project, I enhanced the list of malicious phrases. It is OK if I add them to the existing deny list? I can raise a new PR for the change.

Best,
Aashish

**Comment by redeux** [comment]
> I used the idea behind this project as a basis for a similar project in Python. It is still a work in progress, I hope you don't mind if I release it as an open-source library (with due credits to this project).

Of course not. I'd love to see it.
